data_nodes = [
    {"id": 0, "label": "Atf", "title": "Alaskan Thunder Fuck", "color": "#d44727", "url": "https://www.leafly.com/Sativa/alaskan-thunder-fuck", "value": 1690, "mass": 1},
    {"id": 1, "label": "Amh", "title": "Amnesia Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/amnesia-haze", "value": 1142, "mass": 1},
    {"id": 2, "label": "Bb", "title": "Big Bud", "color": "#6e335e", "url": "https://www.leafly.com/Indica/big-bud", "value": 277, "mass": 4},
    {"id": 3, "label": "Bdm", "title": "Black Domina", "color": "#6e335e", "url": "https://www.leafly.com/Indica/black-domina", "value": 242, "mass": 3},
    {"id": 4, "label": "Bbr", "title": "Blackberry", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/blackberry", "value": 516, "mass": 2},
    {"id": 5, "label": "Bbk", "title": "Blackberry Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/blackberry-kush", "value": 1619, "mass": 1},
    {"id": 6, "label": "Chz", "title": "Blue Cheese", "color": "#6e335e", "url": "https://www.leafly.com/Indica/blue-cheese", "value": 2144, "mass": 1},
    {"id": 7, "label": "Bd", "title": "Blue Dream", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/blue-dream", "value": 11637, "mass": 1},
    {"id": 8, "label": "Bry", "title": "Blueberry", "color": "#6e335e", "url": "https://www.leafly.com/Indica/blueberry", "value": 1698, "mass": 5},
    {"id": 9, "label": "Bk", "title": "Bubba Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/bubba-kush", "value": 2846, "mass": 1},
    {"id": 10, "label": "Cmb", "title": "Cambodian", "color": "#d44727", "url": "https://www.leafly.com/Sativa/cambodian", "value": 6, "mass": 5},
    {"id": 11, "label": "Cah", "title": "Cannalope Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/cannalope-haze", "value": 186, "mass": 2},
    {"id": 12, "label": "Che", "title": "Cheese", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/cheese", "value": 1459, "mass": 1},
    {"id": 13, "label": "Csi", "title": "Chem's Sister", "color": "#d44727", "url": "https://www.leafly.com/Sativa/chems-sister", "value": 16, "mass": 2},
    {"id": 14, "label": "Cd", "title": "Chemdawg", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/chemdawg", "value": 1775, "mass": 12},
    {"id": 15, "label": "C91", "title": "Chemdawg 91", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/chemdawg-91", "value": 116, "mass": 6},
    {"id": 16, "label": "Cp", "title": "Cherry Pie", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/cherry-pie", "value": 1336, "mass": 1},
    {"id": 17, "label": "Cdl", "title": "Chocolate Diesel", "color": "#d44727", "url": "https://www.leafly.com/Sativa/chocolate-diesel", "value": 25, "mass": 2},
    {"id": 18, "label": "Cht", "title": "Chocolate Thai", "color": "#d44727", "url": "https://www.leafly.com/Sativa/chocolate-thai", "value": 77, "mass": 10},
    {"id": 19, "label": "Chc", "title": "Chocolope", "color": "#d44727", "url": "https://www.leafly.com/Sativa/chocolope", "value": 1081, "mass": 1},
    {"id": 20, "label": "Cg", "title": "Colombian Gold", "color": "#d44727", "url": "https://www.leafly.com/Sativa/colombian-gold", "value": 92, "mass": 27},
    {"id": 21, "label": "Ds", "title": "Death Star", "color": "#6e335e", "url": "https://www.leafly.com/Indica/death-star", "value": 1021, "mass": 1},
    {"id": 22, "label": "Dp", "title": "Durban Poison", "color": "#d44727", "url": "https://www.leafly.com/Sativa/durban-poison", "value": 2190, "mass": 3},
    {"id": 23, "label": "G13", "title": "G13", "color": "#6e335e", "url": "https://www.leafly.com/Indica/g-13", "value": 916, "mass": 3},
    {"id": 24, "label": "Gsc", "title": "Girl Scout Cookies", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/girl-scout-cookie", "value": 5838, "mass": 1},
    {"id": 25, "label": "God", "title": "God's Gift", "color": "#6e335e", "url": "https://www.leafly.com/Indica/gods-gift", "value": 1016, "mass": 1},
    {"id": 26, "label": "Gg4", "title": "Gorilla Glue #4", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/gorilla-glue-4", "value": 2804, "mass": 1},
    {"id": 27, "label": "Gdp", "title": "Granddaddy Purple", "color": "#6e335e", "url": "https://www.leafly.com/Indica/granddaddy-purple", "value": 3765, "mass": 3},
    {"id": 28, "label": "Ga", "title": "Grape Ape", "color": "#6e335e", "url": "https://www.leafly.com/Indica/grape-ape", "value": 1665, "mass": 1},
    {"id": 29, "label": "Gc", "title": "Green Crack", "color": "#d44727", "url": "https://www.leafly.com/Sativa/green-crack", "value": 5216, "mass": 1},
    {"id": 30, "label": "Hp", "title": "Hash Plant", "color": "#6e335e", "url": "https://www.leafly.com/Indica/hash-plant", "value": 351, "mass": 4},
    {"id": 31, "label": "Haw", "title": "Hawaiian", "color": "#d44727", "url": "https://www.leafly.com/Sativa/hawaiian", "value": 137, "mass": 4},
    {"id": 32, "label": "H", "title": "Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/haze", "value": 398, "mass": 10},
    {"id": 33, "label": "Hb", "title": "Headband", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/headband", "value": 2253, "mass": 1},
    {"id": 34, "label": "Hk", "title": "Hindu Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/hindu-kush", "value": 905, "mass": 13},
    {"id": 35, "label": "Ice", "title": "Ice", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/ice", "value": 224, "mass": 4},
    {"id": 36, "label": "Jh", "title": "Jack Herer", "color": "#d44727", "url": "https://www.leafly.com/Sativa/jack-herer", "value": 3445, "mass": 1},
    {"id": 37, "label": "Jam", "title": "Jamaican", "color": "#d44727", "url": "https://www.leafly.com/Sativa/jamaican", "value": 42, "mass": 2},
    {"id": 38, "label": "La", "title": "LA Confidential", "color": "#6e335e", "url": "https://www.leafly.com/Indica/la-confidential", "value": 1073, "mass": 1},
    {"id": 39, "label": "Lmg", "title": "Lemon G", "color": "#d44727", "url": "https://www.leafly.com/Sativa/lemon-g", "value": 116, "mass": 2},
    {"id": 40, "label": "Lh", "title": "Lemon Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/lemon-haze", "value": 1908, "mass": 1},
    {"id": 41, "label": "Lk", "title": "Lemon Kush", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/lemon-kush", "value": 1003, "mass": 1},
    {"id": 42, "label": "Ls", "title": "Lemon Skunk", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/lemon-skunk", "value": 693, "mass": 3},
    {"id": 43, "label": "Mks", "title": "Master Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/master-kush", "value": 1517, "mass": 2},
    {"id": 44, "label": "Mw", "title": "Maui Wowie", "color": "#d44727", "url": "https://www.leafly.com/Sativa/maui-wowie", "value": 1176, "mass": 1},
    {"id": 45, "label": "Mis", "title": "Mazar I Sharif", "color": "#6e335e", "url": "https://www.leafly.com/Indica/mazar-i-sharif", "value": 108, "mass": 3},
    {"id": 46, "label": "Mp", "title": "Mendocino Purps", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/mendocino-purps", "value": 243, "mass": 6},
    {"id": 47, "label": "Mex", "title": "Mexican", "color": "#d44727", "url": "https://www.leafly.com/Sativa/mexican", "value": 67, "mass": 18},
    {"id": 48, "label": "Np", "title": "Nepalese", "color": "#d44727", "url": "https://www.leafly.com/Sativa/nepalese", "value": 32, "mass": 13},
    {"id": 49, "label": "Nam", "title": "North American Indica", "color": "#6e335e", "url": "https://www.leafly.com/Indica/north-american", "value": 8, "mass": 8},
    {"id": 50, "label": "Nas", "title": "North American Sativa", "color": "#d44727", "url": "https://www.leafly.com/Sativa/north-american-sativa", "value": 7, "mass": 2},
    {"id": 51, "label": "Nl", "title": "Northern Lights", "color": "#6e335e", "url": "https://www.leafly.com/Indica/northern-lights", "value": 2404, "mass": 16},
    {"id": 52, "label": "N5", "title": "Northern Lights #5", "color": "#6e335e", "url": "https://www.leafly.com/Indica/northern-lights--5", "value": 152, "mass": 7},
    {"id": 53, "label": "Ogk", "title": "OG Kush", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/og-kush", "value": 4632, "mass": 9},
    {"id": 54, "label": "Ola", "title": "OG LA Affie", "color": "#6e335e", "url": "https://www.leafly.com/Indica/og-la-affie", "value": 20, "mass": 2},
    {"id": 55, "label": "Ort", "title": "Ortega", "color": "#6e335e", "url": "https://www.leafly.com/Indica/ortega", "value": 9, "mass": 4},
    {"id": 56, "label": "Pex", "title": "Pineapple Express", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/pineapple-express", "value": 2522, "mass": 1},
    {"id": 57, "label": "Pk", "title": "Purple Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/purple-kush", "value": 1920, "mass": 1},
    {"id": 58, "label": "Pth", "title": "Purple Thai", "color": "#d44727", "url": "https://www.leafly.com/Sativa/purple-thai", "value": 25, "mass": 6},
    {"id": 59, "label": "Pu", "title": "Purple Urkle", "color": "#6e335e", "url": "https://www.leafly.com/Indica/purple-urkle", "value": 987, "mass": 4},
    {"id": 60, "label": "Rbc", "title": "Raspberry Cough", "color": "#d44727", "url": "https://www.leafly.com/Sativa/raspberry-cough", "value": 65, "mass": 3},
    {"id": 61, "label": "Sfv", "title": "SFV OG", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/sfv-og", "value": 413, "mass": 3},
    {"id": 62, "label": "Sfk", "title": "SFV OG Kush", "color": "#6e335e", "url": "https://www.leafly.com/Indica/sfv-og-kush", "value": 162, "mass": 2},
    {"id": 63, "label": "Sen", "title": "Sensi Star", "color": "#6e335e", "url": "https://www.leafly.com/Indica/sensi-star", "value": 533, "mass": 2},
    {"id": 64, "label": "Sh", "title": "Shiva Skunk", "color": "#6e335e", "url": "https://www.leafly.com/Indica/shiva-skunk", "value": 85, "mass": 6},
    {"id": 65, "label": "Slv", "title": "Silver Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/silver-haze", "value": 633, "mass": 2},
    {"id": 66, "label": "Sk1", "title": "Skunk No. 1", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/skunk-1", "value": 399, "mass": 26},
    {"id": 67, "label": "Sky", "title": "Skywalker", "color": "#6e335e", "url": "https://www.leafly.com/Indica/skywalker", "value": 975, "mass": 2},
    {"id": 68, "label": "Sko", "title": "Skywalker OG", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/skywalker-og", "value": 1263, "mass": 1},
    {"id": 69, "label": "Sd", "title": "Sour Diesel", "color": "#d44727", "url": "https://www.leafly.com/Sativa/sour-diesel", "value": 6689, "mass": 5},
    {"id": 70, "label": "Sam", "title": "South American", "color": "#d44727", "url": "https://www.leafly.com/Sativa/south-american", "value": 21, "mass": 37},
    {"id": 71, "label": "Sai", "title": "South Asian Indica", "color": "#6e335e", "url": "https://www.leafly.com/Indica/south-asian", "value": 4, "mass": 2},
    {"id": 72, "label": "Sii", "title": "South Indian Indica", "color": "#6e335e", "url": "https://www.leafly.com/Indica/south-indian-indica", "value": 4, "mass": 3},
    {"id": 73, "label": "Sin", "title": "South Indian Sativa", "color": "#d44727", "url": "https://www.leafly.com/Sativa/south-indian", "value": 10, "mass": 11},
    {"id": 74, "label": "Sc", "title": "Strawberry Cough", "color": "#d44727", "url": "https://www.leafly.com/Sativa/strawberry-cough", "value": 1758, "mass": 1},
    {"id": 75, "label": "Slh", "title": "Super Lemon Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/super-lemon-haze", "value": 1590, "mass": 1},
    {"id": 76, "label": "Ss", "title": "Super Silver Haze", "color": "#d44727", "url": "https://www.leafly.com/Sativa/super-silver-haze", "value": 1805, "mass": 2},
    {"id": 77, "label": "Ssk", "title": "Super Skunk", "color": "#6e335e", "url": "https://www.leafly.com/Indica/super-skunk", "value": 440, "mass": 6},
    {"id": 78, "label": "Tok", "title": "Tahoe OG Kush", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/tahoe-og", "value": 1020, "mass": 1},
    {"id": 79, "label": "Tha", "title": "Thai", "color": "#d44727", "url": "https://www.leafly.com/Sativa/thai", "value": 104, "mass": 45},
    {"id": 80, "label": "Tw", "title": "Trainwreck", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/trainwreck", "value": 2481, "mass": 2},
    {"id": 81, "label": "Uk", "title": "UK Cheese", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/uk-cheese", "value": 471, "mass": 2},
    {"id": 82, "label": "Wr", "title": "White Rhino", "color": "#6e335e", "url": "https://www.leafly.com/Indica/white-rhino", "value": 1020, "mass": 1},
    {"id": 83, "label": "Ww", "title": "White Widow", "color": "#76bd1d", "url": "https://www.leafly.com/Hybrid/white-widow", "value": 3507, "mass": 2},
];

data_edges = [
    {"from": 2, "to": 27},
    {"from": 3, "to": 4},
    {"from": 4, "to": 5},
    {"from": 8, "to": 6},
    {"from": 8, "to": 7},
    {"from": 8, "to": 67},
    {"from": 10, "to": 1},
    {"from": 10, "to": 60},
    {"from": 11, "to": 19},
    {"from": 13, "to": 26},
    {"from": 14, "to": 13},
    {"from": 14, "to": 53},
    {"from": 15, "to": 69},
    {"from": 17, "to": 26},
    {"from": 18, "to": 17},
    {"from": 18, "to": 19},
    {"from": 18, "to": 58},
    {"from": 20, "to": 66},
    {"from": 22, "to": 16},
    {"from": 22, "to": 24},
    {"from": 23, "to": 39},
    {"from": 27, "to": 16},
    {"from": 27, "to": 25},
    {"from": 30, "to": 3},
    {"from": 31, "to": 1},
    {"from": 31, "to": 44},
    {"from": 31, "to": 56},
    {"from": 32, "to": 1},
    {"from": 32, "to": 7},
    {"from": 32, "to": 11},
    {"from": 32, "to": 36},
    {"from": 32, "to": 65},
    {"from": 32, "to": 76},
    {"from": 34, "to": 43},
    {"from": 34, "to": 53},
    {"from": 34, "to": 57},
    {"from": 35, "to": 60},
    {"from": 37, "to": 1},
    {"from": 39, "to": 41},
    {"from": 42, "to": 40},
    {"from": 42, "to": 75},
    {"from": 43, "to": 41},
    {"from": 45, "to": 67},
    {"from": 46, "to": 28},
    {"from": 46, "to": 59},
    {"from": 47, "to": 11},
    {"from": 47, "to": 32},
    {"from": 47, "to": 58},
    {"from": 47, "to": 80},
    {"from": 48, "to": 14},
    {"from": 49, "to": 46},
    {"from": 49, "to": 82},
    {"from": 50, "to": 0},
    {"from": 51, "to": 2},
    {"from": 51, "to": 3},
    {"from": 51, "to": 30},
    {"from": 51, "to": 35},
    {"from": 51, "to": 55},
    {"from": 51, "to": 65},
    {"from": 51, "to": 76},
    {"from": 52, "to": 36},
    {"from": 52, "to": 64},
    {"from": 53, "to": 9},
    {"from": 53, "to": 24},
    {"from": 53, "to": 25},
    {"from": 53, "to": 33},
    {"from": 53, "to": 61},
    {"from": 53, "to": 68},
    {"from": 53, "to": 78},
    {"from": 54, "to": 38},
    {"from": 55, "to": 3},
    {"from": 58, "to": 8},
    {"from": 59, "to": 27},
    {"from": 60, "to": 4},
    {"from": 61, "to": 62},
    {"from": 62, "to": 78},
    {"from": 63, "to": 21},
    {"from": 64, "to": 35},
    {"from": 64, "to": 36},
    {"from": 65, "to": 40},
    {"from": 66, "to": 2},
    {"from": 66, "to": 12},
    {"from": 66, "to": 28},
    {"from": 66, "to": 29},
    {"from": 66, "to": 35},
    {"from": 66, "to": 42},
    {"from": 66, "to": 64},
    {"from": 66, "to": 76},
    {"from": 66, "to": 77},
    {"from": 66, "to": 81},
    {"from": 67, "to": 68},
    {"from": 69, "to": 17},
    {"from": 69, "to": 21},
    {"from": 69, "to": 33},
    {"from": 70, "to": 20},
    {"from": 70, "to": 32},
    {"from": 70, "to": 41},
    {"from": 70, "to": 83},
    {"from": 71, "to": 1},
    {"from": 72, "to": 83},
    {"from": 73, "to": 32},
    {"from": 76, "to": 75},
    {"from": 77, "to": 69},
    {"from": 79, "to": 1},
    {"from": 79, "to": 8},
    {"from": 79, "to": 14},
    {"from": 79, "to": 15},
    {"from": 79, "to": 18},
    {"from": 79, "to": 32},
    {"from": 79, "to": 51},
    {"from": 79, "to": 80},
    {"from": 80, "to": 56},
    {"from": 81, "to": 6},
    {"from": 83, "to": 82},
];
